### ISSUE TITLE
Spotify reopens after closing down the application

### ISSUE THREAD

**Issue by ddavidtran** [GoldenChaos/GoldenChaos-BTT#1]
Hi,

When using GoldenChaos-BTT there is a bug when you launch Spotify and then decide to quit the app, the application will automatically relaunch. 

Reproduce steps:
Preset: GoldenChaos-BTT 2.536-4

1. Close down the application BTT.
2. Quit the Spotify application.
3. Relaunch BTT and use GoldenChaos-BTT 2.536-4 as preset.
4. Launch Spotify and then attempt to close it.

**Comment by ConorTheDev** [comment]
I'm having this on Normal Spotify :(

**Comment by GoldenChaos** [comment]
Oh hey this was fixed in 2.641! Closing this :)
