### ISSUE TITLE
Volume Icon is missing volume bars after unmute

### ISSUE THREAD

**Issue by tbrodbeck** [GoldenChaos/GoldenChaos-BTT#10]
Hey, I really like that there is a volume icon in my touchbar that shows 1, 2 or 3 bars depending on the current volume. (I am speaking about the icon with the volume up functionality by default).

When my volume is muted, it shows no volume bars at all, which is nice. But when I unmute my volume after that, it does not refresh and does not display the respecting 1,2 or 3 bars anymore.
(Only when I change my volume up or down it does redisplay the bars.)

Can you reproduce that? 
I have to say, that it works very rarely. But most of the time it does not.
So far I could not find any bugs in the apple script, but I do not fully understand it tbh.

**Comment by GoldenChaos** [comment]
Will look into this and report back!

**Comment by GoldenChaos** [comment]
@tbrodbeck I'm not experiencing this issue on GC-BTT 3.335 (new version I recently released). Is this issue still occurring for you?

**Comment by tbrodbeck** [comment]
To install GC-BTT 3.335 I needed to install the 3.335 Version of BTT itself first. This already fixed the issue! Thanks for letting me know :)
