### ISSUE TITLE
Disappearing icons for new tab and refresh

### ISSUE THREAD

**Issue by nikola-kovacevic** [GoldenChaos/GoldenChaos-BTT#15]
Let me start by saying good work on your project. It makes the Mac touch bar more usable and fancy.

The main issue I am experiencing is disappearing icons for the Refresh and New tab. Their placeholders are visible, the only thing that is missing is the actual icon.

My OS is Catalina 10.15.4 and I am running the latest BTT, with GoldenChaos-BTT version 3.368.

There are two other less important issues that I noticed:
- if you enable Use Normal Escape key the button that shows looks weird, it has big padding on the left of `esc`.
- Collapse/Expand Menu Bar Control is quite sluggish - it takes 2-3 secs before the action is executed

**Comment by GoldenChaos** [comment]
This *should* be fixed in 3.392, since I had to audit the logic for these buttons. Can you confirm if things are fixed? 😄

**Comment by nikola-kovacevic** [comment]
the icons are there now 👍 thank you
