### ISSUE TITLE
Can hide right space when hold command btn?

### ISSUE THREAD

**Issue by HotdogWang** [GoldenChaos/GoldenChaos-BTT#3]
Hi

I ready love the present you provide for BTT touch bar.

I have a question for when I hold command btn it will display APP on Touch bar.
I cancel all right space btn, but it still show a black space on Touch bar like below image.
<img width="1085" alt="2018-11-04 2 36 07" src="https://user-images.githubusercontent.com/12172172/47961247-20598080-e042-11e8-9865-47dd42647edc.png">

Is it passable to hide black space when I hold the command, and how to setting?
Thanks! 😀

**Comment by GoldenChaos** [comment]
Answered on the BTT forums! Cheers 😄
