### ISSUE TITLE
Selectively disable modifier menus

### ISSUE THREAD

**Issue by camscofie** [GoldenChaos/GoldenChaos-BTT#4]
Hello, I want to ask if I can disable the control menu (press and hold the control and the touch bar will be different).

Thanks

**Comment by GoldenChaos** [comment]
I plan on adding a setting for this in a future version! Please subscribe to the release thread for updates :) https://community.folivora.ai/t/goldenchaos-btt-a-complete-touch-bar-ui-replacement-preset/1281

**Comment by jcherrera** [comment]
can you disable the command menu?

**Comment by GoldenChaos** [comment]
It’s still in the works! Right now I’m working on the new settings window, so this will come sometime after that. It’s definitely the next big top priority feature.

**Comment by GoldenChaos** [comment]
This feature has existed for a while! Closing :D
