### ISSUE TITLE
"Telegram Desktop" support for Telegram dock badge

### ISSUE THREAD

**Issue by Maxinho96** [GoldenChaos/GoldenChaos-BTT#5]
Currently, only "Telegram" app is supported for dock badges, but "Telegram Desktop" is not. I have solved by adding a BTT script which is the same as the "Telegram" script, with the app name changed to "Telegram Desktop". It would be nice if it will be supported out of the box with the next release.

**Comment by GoldenChaos** [comment]
Thank you for reporting this! I've fixed this locally and it'll go out with the next build. :)

**Comment by GoldenChaos** [comment]
Actually, I think I can make the Telegram badge support both versions, so I'm gonna do that!

**Comment by GoldenChaos** [comment]
This was added in GC-BTT 3.187, which was released earlier today! Give it a shot 🙂

**Comment by Maxinho96** [comment]
Awesome 👏🏼
