### ISSUE TITLE
Full screen option in Home Strip window snapping

### ISSUE THREAD

**Issue by kostyan5** [GoldenChaos/GoldenChaos-BTT#6]
Would like a full screen button (in addition or in-place of center of screen) for window snapping options in the Home Strip.  I find center snap is relatively useless as it takes up most of the screen but doesn't fill the entire screen.

**Comment by GoldenChaos** [comment]
Hey there! I answered this in the GC-BTT support thread: https://community.folivora.ai/t/goldenchaos-btt-support-and-feedback-thread/5196/1670?u=goldenchaos

Hopefully that answers your question!
