### ISSUE TITLE
Airpods Pro support

### ISSUE THREAD

**Issue by diegoscl** [GoldenChaos/GoldenChaos-BTT#9]
At this time activating the "Connect to Airpods" option in the menu bar can display the status of the connection, but pressing the button does not cause anything (Do not connect or disconnect Airpods Pro).

**Comment by GoldenChaos** [comment]
Working on this for the next update!

**Comment by GoldenChaos** [comment]
This was FINALLY added in GC-BTT 3.335. Thank you for being so patient!
